# version: '3.8'

# services:
#   frontend:
#     build: .
#     container_name: fronted-techniza
#     ports:
#       - "80:80"
#     restart: always

version: '3.8'

services:
  frontend:
    build: .
    container_name: fronted-techniza
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/admin.techniza.mx/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/admin.techniza.mx/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: always